spring:
  datasource:
    driver-calss-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
